In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
df = pd.read_csv('GDELT_2017/cleaned_jan.csv')

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
df.head()

,Unnamed: 0,Unnamed: 0.1,content,day,event_code,lat,long,month,place,time,title,url,year,sentiment_pos,sentiment_neg,sentiment_neu,sentiment_compound,sentiment_textblob,date
0,0,0,Bringing to an end the musical chairs game for...,1.0,40.0,28.6000,77.2000,1.0,IN,"Updated: January 1, 2017 11:34:40 am","In Arunachal, CM Pema Khandu wins musical chai...",http://indianexpress.com/article/india/in-arun...,2017.0,0.137,0.038,0.825,0.9965,0.082525,1-1-2017
1,1,1,MUMBAI: Request for a seat share landed a yout...,1.0,180.0,19.6833,72.7500,1.0,IN,NaN,Mumbaikar brutally assaulted in Dahanu local o...,http://timesofindia.indiatimes.com/city/mumbai...,2017.0,0.036,0.176,0.788,-0.9881,-0.255785,1-1-2017
2,2,2,The CIA staff of the Mohali police on Saturday...,1.0,173.0,24.1492,78.9817,1.0,IN,"Published: January 1, 2017 5:00:13 am",Two held with 2 kg heroin worth Rs 5 crore in ...,http://indianexpress.com/article/cities/chandi...,2017.0,0.023,0.180,0.797,-0.9790,0.105556,1-1-2017
3,3,3,THE PREDICTION of snowfall on New Years Eve dr...,1.0,120.0,31.9167,77.2500,1.0,IN,"Published: January 1, 2017 5:02:08 am","Tourists descend in hope of snow, Shimla feels...",http://indianexpress.com/article/cities/chandi...,2017.0,0.052,0.035,0.913,0.8085,0.135787,1-1-2017
4,4,4,This was the year when old certainties crumble...,1.0,42.0,18.9750,72.8258,1.0,IN,"Updated: January 1, 2017 12:46:58 pm",The Future of the Future: EYE 2017 special issue,http://indianexpress.com/article/lifestyle/lif...,2017.0,0.086,0.051,0.863,0.9431,0.096080,1-1-2017

In [5]:
lst = df['13']

In [20]:
websites = []
count=0
for l in lst:
    try:
        website = str(l).split('/')[2]
        websites.append(website)
    except:
        count+=1

In [24]:
websites = list(set(websites))

In [27]:
np.savetxt("websites_jan_gdelt.csv", websites, delimiter=",", fmt='%s')

In [2]:
df = pd.read_csv('GDELT_2017/unrest_gdelt_2017_sentiment.csv')

In [5]:
df['date'] = ''
for i,row in df.iterrows():
    date = ''
    day = int(row['day'])
    month = int(row['month'])
    year = int(row['year'])
    date = str(day)+'-'+str(month)+'-'+str(year)
    df.set_value(i,'date',date)

In [7]:
df.to_csv('GDELT_2017/unrest_gdelt_2017_sentiment.csv')

In [8]:
d = pd.read_csv('GDELT_2017/unrest_gdelt_2017_sentiment.csv')

In [9]:
d.head()

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,content,day,event_code,lat,long,month,place,time,title,url,year,sentiment_pos,sentiment_neg,sentiment_neu,sentiment_compound,sentiment_textblob,date
0,0,0,0,Bringing to an end the musical chairs game for...,1.0,40.0,28.6000,77.2000,1.0,IN,"Updated: January 1, 2017 11:34:40 am","In Arunachal, CM Pema Khandu wins musical chai...",http://indianexpress.com/article/india/in-arun...,2017.0,0.137,0.038,0.825,0.9965,0.082525,1-1-2017
1,1,1,1,MUMBAI: Request for a seat share landed a yout...,1.0,180.0,19.6833,72.7500,1.0,IN,NaN,Mumbaikar brutally assaulted in Dahanu local o...,http://timesofindia.indiatimes.com/city/mumbai...,2017.0,0.036,0.176,0.788,-0.9881,-0.255785,1-1-2017
2,2,2,2,The CIA staff of the Mohali police on Saturday...,1.0,173.0,24.1492,78.9817,1.0,IN,"Published: January 1, 2017 5:00:13 am",Two held with 2 kg heroin worth Rs 5 crore in ...,http://indianexpress.com/article/cities/chandi...,2017.0,0.023,0.180,0.797,-0.9790,0.105556,1-1-2017
3,3,3,3,THE PREDICTION of snowfall on New Years Eve dr...,1.0,120.0,31.9167,77.2500,1.0,IN,"Published: January 1, 2017 5:02:08 am","Tourists descend in hope of snow, Shimla feels...",http://indianexpress.com/article/cities/chandi...,2017.0,0.052,0.035,0.913,0.8085,0.135787,1-1-2017
4,4,4,4,This was the year when old certainties crumble...,1.0,42.0,18.9750,72.8258,1.0,IN,"Updated: January 1, 2017 12:46:58 pm",The Future of the Future: EYE 2017 special issue,http://indianexpress.com/article/lifestyle/lif...,2017.0,0.086,0.051,0.863,0.9431,0.096080,1-1-2017